# Generated by Django 4.2.19 on 2025-03-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
